In [1]:
#Bai Tap Tren Lop
# Bai 1 Viết chương trình nhập vào 2 giá trị a, b và tính tổng, hiệu, tích thương của a và b.
a = int(input("Nhap vao gia tri a: "))
b = int(input("Nhap vao gia tri b: "))
phepcong = a + b
pheptru = a - b
phepnhan = a * b
phepchia = a / b if b != 0 else "Khong chia duoc"
print("\n phep cong: ", phepcong)
print("\n phep tru: ", pheptru)
print("\n phep nhan: ", phepnhan)
print("\n phep chia: ", phepchia)

Nhap vao gia tri a: 4
Nhap vao gia tri b: 5

 phep cong:  9

 phep tru:  -1

 phep nhan:  20

 phep chia:  0.8


In [2]:
# Bai 2 Lấy các ký tự từ chỉ số 2 đến chỉ số 4 (llo) của chuỗi “Hello World”.
string = input("\nNhap Chuoi: ")
print(string[2:5])


Nhap Chuoi: HelloWorld
llo


In [3]:
# Bai 3 Xóa khoảng trắng thừa ở đầu và cuối chuỗi “ Hello World ”. Chuyển chuỗi sang dạng hoa và thường. Thay ký tự H thành ký tự J.
original_string = " Hello World "
print(f"Original string: '{original_string}'")

stripped_string = original_string.strip()
print(f"String after stripping whitespace: '{stripped_string}'")

uppercase_string = stripped_string.upper()
print(f"String in uppercase: '{uppercase_string}'")

lowercase_string = stripped_string.lower()
print(f"String in lowercase: '{lowercase_string}'")

replaced_string = stripped_string.replace('H', 'J')
print(f"String after replacing 'H' with 'J': '{replaced_string}'")

Original string: ' Hello World '
String after stripping whitespace: 'Hello World'
String in uppercase: 'HELLO WORLD'
String in lowercase: 'hello world'
String after replacing 'H' with 'J': 'Jello World'


In [4]:
# Bai 4 In ra “Hello World!” nếu a lớn hơn b.
a1 = int(input("Nhap vao gia tri a: "))
b1 = int(input("Nhap vao gia tri b: "))
if a1 > b1:
    print("Hello World!")

Nhap vao gia tri a: 4
Nhap vao gia tri b: 3
Hello World!


In [5]:
#Bai 5 In ra “Yes” nếu a bằng b, ngược lại in “No”.
a2 = int(input("Nhap vao gia tri a: "))
b2 = int(input("Nhap vao gia tri b: "))
if a2 == b2:
    print("Yes")
else:
    print("No")

Nhap vao gia tri a: 3
Nhap vao gia tri b: 3
Yes


In [6]:
#Bai 6 In 1 nếu a bằng b, in 2 nếu a > b, in 3 nếu ngược lại.
a = int(input("Nhap vao gia tri a: "))
b = int(input("Nhap vao gia tri b: "))
if a == b:
    print(1)
elif a > b:
    print(2)
else:
    print(3)

Nhap vao gia tri a: 4
Nhap vao gia tri b: 5
3


In [7]:
#bai 7 In ra “Hello World!” nếu a bằng b và b bằng d.
a = int(input("Nhap vao gia tri a: "))
b = int(input("Nhap vao gia tri b: "))
d = int(input("Nhap vao gia tri d: "))
if a == b and b == d:
    print("HelloWorld")

Nhap vao gia tri a: 3
Nhap vao gia tri b: 3
Nhap vao gia tri d: 3
HelloWorld


In [8]:
#Bai 8 In ra “Hello World!” nếu a bằng b hoặc c bằng d.
a = int(input("Nhap vao gia tri a: "))
b = int(input("Nhap vao gia tri b: "))
c = int(input("Nhap vao gia tri c: "))
d = int(input("Nhap vao gia tri d: "))
if a == b or c == d:
    print("HelloWorld")

Nhap vao gia tri a: 3
Nhap vao gia tri b: 4
Nhap vao gia tri c: 5
Nhap vao gia tri d: 5
HelloWorld


In [9]:
#Bai 9
a = int(input("Nhap vao gia tri a: "))
b = int(input("Nhap vao gia tri b: "))
print('yes' if a > b else 'No')

Nhap vao gia tri a: 3
Nhap vao gia tri b: 1
yes


In [10]:
#Bai 10
a = int(input("Nhap vao gia tri a: "))
b = int(input("Nhap vao gia tri b: "))
print('A' if a > b else '=' if a == b else 'B')

Nhap vao gia tri a: 4
Nhap vao gia tri b: 3
A


In [11]:
#Bai 11
e = int(input("nhap vao n phan tu vao mang a: "))
import numpy as np
manga = np.random.randint(0, 100, e)
mangb = []
for element in manga:
    if element % 2 == 0:
        mangb.append(True)
    else:
        mangb.append(False)
newmangb = np.array(mangb)
print(manga)
print(newmangb)

nhap vao n phan tu vao mang a: 4
[22 38 66 15]
[ True  True  True False]


In [12]:
#Bai 12
sum_val = 0
n = 999
for i in range(n + 1):
    if i % 5 == 0 or i % 3 == 0:
        sum_val += i
print("Tong cac so tu 0 den 999 ma la boi cua 5 hoac 3 la: ", sum_val)

Tong cac so tu 0 den 999 ma la boi cua 5 hoac 3 la:  233168


In [13]:
#Bai 13
a = [14, 12, 20, 6]
b = [21, 12, 20, 6, 12, 5]
min_len = len(b) if len(a) > len(b) else len(a)
c = []
for i in range(min_len):
    c.append(a[i] + b[i])
if len(a) > len(b):
    c.extend(a[min_len:])
else:
    c.extend(b[min_len:])
print(c)

[35, 24, 40, 12, 12, 5]


In [15]:
#Bai 14
import numpy as np
m = int(input("Nhap vao m dong: "))
n = int(input("Nhap vao n cot: "))
#Cau a
manganew = np.random.rand(m,n)
print("mang a sau khi random: ",manganew)

#Cau b
k = int(input("nhap vao dong k ma ban muon: "))
if 0 <= k < m:
    print("\nCac phan tu thuoc dong k: ", manganew[k])

#Cau c:
k1 = int(input("nhap vao cot k ma ban muon lay ra: "))
if 0 <= k1 < n:
    k1_col = [row[k1] for row in manganew]
    print("\n cac phan tu thuoc cot k la: ", k1_col)

#Cau d:
row_sums = np.sum(manganew, axis=1)
max_row_index = np.argmax(row_sums)
print("\nDong co tong lon nhat la:", manganew[max_row_index])
print("Tong cua dong do la:", row_sums[max_row_index])

#cau e:
col_products = np.prod(manganew, axis=0)
min_col_index = np.argmin(col_products)
print("\nCot co tich nho nhat la:", manganew[:, min_col_index])
print("Tich cua cot do la:", col_products[min_col_index])

#cau f:
print("\nCac phan tu thuoc dong chan va cot le:")
for i in range(m):
    for j in range(n):
        if i % 2 == 0 and j % 2 != 0:
            print(f"a[{i}][{j}] = {manganew[i][j]}")

#cau g:
mang_chan_dong_le = []
for i in range(m):
    if i % 2 != 0:
        for j in range(n):
            if int(manganew[i][j]) % 2 == 0:
                mang_chan_dong_le.append(manganew[i][j])
if len(mang_chan_dong_le) > 0:
    print("\nTrung binh cong:", sum(mang_chan_dong_le)/len(mang_chan_dong_le))

#Cau h:
mang_bien = []
for i in range(m):
    for j in range(n):
        if i == 0 or i == m-1 or j == 0 or j == n-1:
            mang_bien.append(manganew[i][j])
print("\nTrung binh cong bien:", sum(mang_bien)/len(mang_bien))

#cau i:
mang_trong = []
for i in range(1, m-1):
    for j in range(1, n-1):
        mang_trong.append(manganew[i][j])
if len(mang_trong) > 0:
    tich = 1
    for x in mang_trong:
        tich *= x
    print("\nTrung binh tich:", tich ** (1/len(mang_trong)))


Nhap vao m dong: 4
Nhap vao n cot: 4
mang a sau khi random:  [[0.21112735 0.82025697 0.22800343 0.61840822]
 [0.07499621 0.71497604 0.31354366 0.52118729]
 [0.33068527 0.48318163 0.23096582 0.20361413]
 [0.41466666 0.59136061 0.89326746 0.47737832]]
nhap vao dong k ma ban muon: 4
nhap vao cot k ma ban muon lay ra: 4

Dong co tong lon nhat la: [0.41466666 0.59136061 0.89326746 0.47737832]
Tong cua dong do la: 2.376673050756595

Cot co tich nho nhat la: [0.21112735 0.07499621 0.33068527 0.41466666]
Tich cua cot do la: 0.002171189842676716

Cac phan tu thuoc dong chan va cot le:
a[0][1] = 0.8202569657756325
a[0][3] = 0.6184082217273276
a[2][1] = 0.4831816295886331
a[2][3] = 0.20361412691636238

Trung binh cong: 0.5001720322323282

Trung binh cong bien: 0.4487459927400079

Trung binh tich: 0.39770578569787507


In [16]:
#Bai 15
class SinhVien:
    def __init__(self, n):
        self.dic_SinhVien = {'maSV': [], 'hoTen': [], 'namsinh': [], 'diemTB': []}
        for i in range(n):
            self.dic_SinhVien['maSV'].append(input("Nhap ma SV: "))
            self.dic_SinhVien['hoTen'].append(input("Nhap ho ten: "))
            self.dic_SinhVien['namsinh'].append(int(input("Nhap nam sinh: ")))
            self.dic_SinhVien['diemTB'].append(float(input("Nhap diem: ")))

sv_manager = SinhVien(2)
print(sv_manager.dic_SinhVien)

#c
def check_pass(dic):
    return sum(d >= 5 for d in dic['diemTB'])
print(check_pass(sv_manager.dic_SinhVien))

#d
def check_age(dic):
    for i in range(len(dic['namsinh'])):
        if 2026 - dic['namsinh'][i] >= 20:
            print(dic['hoTen'][i])
check_age(sv_manager.dic_SinhVien)

#e
def count_dh_students(dic):
    return sum(len(ma)>=4 and ma[2:4].upper()=="DH" for ma in dic['maSV'])
print(count_dh_students(sv_manager.dic_SinhVien))

#f
def count_name_lan(dic):
    return sum(name.split()[-1].lower()=="lan" for name in dic['hoTen'])
print(count_name_lan(sv_manager.dic_SinhVien))

#g
def count_surname_phan(dic):
    return sum(name.split()[0].lower()=="phan" for name in dic['hoTen'])
print(count_surname_phan(sv_manager.dic_SinhVien))

Nhap ma SV: SV001
Nhap ho ten: LeDinhMinhQuang
Nhap nam sinh: 2006
Nhap diem: 7.32
Nhap ma SV: SV002
Nhap ho ten: LeMinhQuang
Nhap nam sinh: 2005
Nhap diem: 8.43
{'maSV': ['SV001', 'SV002'], 'hoTen': ['LeDinhMinhQuang', 'LeMinhQuang'], 'namsinh': [2006, 2005], 'diemTB': [7.32, 8.43]}
2
LeDinhMinhQuang
LeMinhQuang
0
0
0
